### ISSUE TITLE
ColorPicker does not get document's colors and doesn't Saving New Colors in Documents

### ISSUE THREAD

**Issue by emirmorris** [nvzone/minty#12] opened 2024-10-27 23:56 UTC
I’ve recently updaded to NVChad 3.0 and wanna use Minty plugin. I've configured and add mapping for huefy as <C-T>. But it doesn't work properly. While I place my cursor over a six-character color code the huefy-popup opens correctly but :

1. 	The Old Color in the Color Picker window defaults to blue instead of showing my currently color in the document where my cursor is located (white).
2. 	When I select a New Color in the Color Picker, this color doesn’t replace the color code in the document, nor does it save as expected.

Here are the details of my setup and steps to reproduce:

Steps to Reproduce:

1. 	Open a document with a six-character hex color code (e.g., #FFFFFF).
2. 	Place the cursor on the color code.
3. 	Press CTRL-T to open the Color Picker.
4. 	Observe that the Old Color does not match the document color and defaults to blue.
5. 	Select a new color in the Color Picker and attempt to save it.
6. 	Notice that the new color is not updated back into the document.

Expected Behavior:

- The Old Color in the Color Picker should match the color code currently in the document where the cursor is located.
- After selecting a New Color in the Color Picker and saving it, the color code in the document should update to the new color.

	
P.S: With "Shades" it doesn't work either.

Please let me know if there is any additional information or debugging steps I can provide. Thank you!

**Comment by emirmorris** [comment] 2024-10-28 04:19
Yes. 

https://github.com/user-attachments/assets/6523c6e7-d9c4-41c7-b6ef-16d10731f234

Settings are default:

```
  {
    "nvchad/volt",
    lazy = true,
  },

  {
    "nvchad/minty",
    cmd = { "Shades", "Huefy" },
  },
```

**Comment by emirmorris** [comment] 2024-10-28 04:59
> weird, still unable to reproduce, is your cursor position shifted 🤔

Nope. I click on that color (#FFFFFF).

**Comment by siduck** [comment] 2024-10-28 05:34
have u done lazy sync

**Comment by emirmorris** [comment] 2024-10-28 05:43
> have u done lazy sync

Yes

**Comment by siduck** [comment] 2024-10-28 05:57
can you try this on vanilla nvchad? idk why i feel like some plugin's shifting the cursor pos :thinking:

**Comment by emirmorris** [comment] 2024-10-29 12:15
I don't know what is vanilla nvchad

**Comment by siduck** [comment] 2024-10-29 14:55
just nvchad, without any plugins. Only you're facing this issue, cant reproduce it so I'm unable to   help.

**Comment by Spell28** [comment] 2024-11-29 21:56
same problem in vanilla nvchad

**Comment by siduck** [comment] 2024-11-30 01:10
unable to reproduce -__-

**Comment by siduck** [comment] 2024-11-30 01:11
> same problem in vanilla nvchad

show video

**Comment by Spell28** [comment] 2024-11-30 07:57
I found the problem. Before that, I checked in the tsx component and it doesn't work.
But in css everything works as it should

https://github.com/user-attachments/assets/dc552d31-0cd1-4647-b2e8-42728b19c899

**Closed** 2024-11-30 15:20 UTC
